/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        get: operations["api_v1_applications_list"];
        put?: never;
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        post: operations["api_v1_applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        get: operations["api_v1_applications_retrieve"];
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        put: operations["api_v1_applications_update"];
        post?: never;
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        delete: operations["api_v1_applications_destroy"];
        options?: never;
        head?: never;
        /** @description The user's application tracker rows. Full CRUD on own rows only.
         *
         *     A status change automatically appends a timeline event, so the
         *     history stays complete without extra bookkeeping. */
        patch: operations["api_v1_applications_partial_update"];
        trace?: never;
    };
    "/api/v1/applications/{id}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Append a note/event to the application's timeline. */
        post: operations["api_v1_applications_events_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download the tracker as CSV (filters apply). */
        get: operations["api_v1_applications_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/tracked-urls/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All ad URLs on the user's board — lets the ad search mark
         *     already-saved ads without downloading every application row. */
        get: operations["api_v1_applications_tracked_urls_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Live search of Platsbanken via JobTech, with optional CV matching. */
        get: operations["api_v1_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Region and occupation-field options for the ad-search dropdowns. */
        get: operations["api_v1_jobs_filters_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Occupation-group options for one selected occupation field. */
        get: operations["api_v1_jobs_groups_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/municipalities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Municipality options for one selected region. */
        get: operations["api_v1_jobs_municipalities_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated user's own profile.
         *
         *     GET returns contact details. PATCH updates them. DELETE erases the
         *     account and everything it owns (GDPR right to erasure). */
        get: operations["api_v1_me_retrieve"];
        /** @description The authenticated user's own profile.
         *
         *     GET returns contact details. PATCH updates them. DELETE erases the
         *     account and everything it owns (GDPR right to erasure). */
        put: operations["api_v1_me_update"];
        post?: never;
        /** @description The authenticated user's own profile.
         *
         *     GET returns contact details. PATCH updates them. DELETE erases the
         *     account and everything it owns (GDPR right to erasure). */
        delete: operations["api_v1_me_destroy"];
        options?: never;
        head?: never;
        /** @description The authenticated user's own profile.
         *
         *     GET returns contact details. PATCH updates them. DELETE erases the
         *     account and everything it owns (GDPR right to erasure). */
        patch: operations["api_v1_me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/resume/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated user's structured CV (created empty on first GET). */
        get: operations["api_v1_me_resume_retrieve"];
        /** @description The authenticated user's structured CV (created empty on first GET). */
        put: operations["api_v1_me_resume_update"];
        post?: never;
        /** @description The authenticated user's structured CV (created empty on first GET). */
        delete: operations["api_v1_me_resume_destroy"];
        options?: never;
        head?: never;
        /** @description The authenticated user's structured CV (created empty on first GET). */
        patch: operations["api_v1_me_resume_partial_update"];
        trace?: never;
    };
    "/api/v1/me/resume/parse/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Parse an uploaded CV (PDF/DOCX/TXT) into a structured draft.
         *
         *     The file is processed in memory and never stored; nothing is saved
         *     until the user reviews the prefilled form and submits it. */
        post: operations["api_v1_me_resume_parse_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/resume/suggest-evidence/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Suggest evidence terms keyed by CV source row. */
        post: operations["api_v1_me_resume_suggest_evidence_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/resume/suggest-skills/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Suggest categorized skills extracted from experience rows. */
        post: operations["api_v1_me_resume_suggest_skills_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/saved-searches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List or save Platsbanken search presets for the current user. */
        get: operations["api_v1_me_saved_searches_list"];
        put?: never;
        /** @description List or save Platsbanken search presets for the current user. */
        post: operations["api_v1_me_saved_searches_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/saved-searches/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_me_saved_searches_retrieve"];
        put?: never;
        post?: never;
        delete: operations["api_v1_me_saved_searches_destroy"];
        options?: never;
        head?: never;
        patch: operations["api_v1_me_saved_searches_partial_update"];
        trace?: never;
    };
    "/dj-rest-auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Exchange a Google authorization code for our JWT pair.
         *
         *     The SPA redirects the user to Google's consent screen and posts the
         *     returned ``code`` here. Requires GOOGLE_CLIENT_ID/SECRET in the
         *     environment (the button is hidden in the SPA when unset). */
        post: operations["dj_rest_auth_google_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Check the credentials and return the REST Token
         *     if the credentials are valid and authenticated.
         *     Calls Django Auth login method to register User ID
         *     in Django session framework
         *
         *     Accept the following POST parameters: username, password
         *     Return the REST Framework Token Object's key. */
        post: operations["dj_rest_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Calls Django logout method and delete the Token object
         *     assigned to the current User object.
         *
         *     Accepts/Returns nothing. */
        post: operations["dj_rest_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Calls Django Auth SetPasswordForm save method.
         *
         *     Accepts the following POST parameters: new_password1, new_password2
         *     Returns the success/fail message. */
        post: operations["dj_rest_auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Calls Django Auth PasswordResetForm save method.
         *
         *     Accepts the following POST parameters: email
         *     Returns the success/fail message. */
        post: operations["dj_rest_auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Password reset e-mail link is confirmed, therefore
         *     this resets the user's password.
         *
         *     Accepts the following POST parameters: token, uid,
         *         new_password1, new_password2
         *     Returns the success/fail message. */
        post: operations["dj_rest_auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/registration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register without issuing JWT — user must verify e-mail first. */
        post: operations["dj_rest_auth_registration_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/registration/account-confirm-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dj_rest_auth_registration_account_confirm_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/registration/resend-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dj_rest_auth_registration_resend_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/registration/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dj_rest_auth_registration_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid. */
        post: operations["dj_rest_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use. */
        post: operations["dj_rest_auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dj-rest-auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields. */
        get: operations["dj_rest_auth_user_retrieve"];
        /** @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields. */
        put: operations["dj_rest_auth_user_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields. */
        patch: operations["dj_rest_auth_user_partial_update"];
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public health check endpoint. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationEvent: {
            readonly id: number;
            /** Format: date */
            occurred_at: string;
            note: string;
            status?: components["schemas"]["StatusEnum"] | components["schemas"]["BlankEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description Registration by e-mail only — no username field in the API.
         *
         *     Enforce e-mail uniqueness here so an abandoned unverified signup
         *     cannot be silently replaced by a new registration attempt. */
        EmailRegister: {
            /** Format: email */
            email: string;
            password1: string;
            password2: string;
        };
        /** @description Send the reset link to the SPA rather than Django's default view.
         *
         *     allauth's reset form takes a custom ``url_generator``; ours points the
         *     e-mailed link at the SPA carrying uid + token as query params, which
         *     the app reads to show the set-new-password form. */
        FrontendPasswordReset: {
            /** Format: email */
            email: string;
        };
        /** @description Serializer for JWT authentication. */
        JWT: {
            access: string;
            refresh: string;
            user: components["schemas"]["UserDetails"];
        };
        /** @description One tracker row.
         *
         *     Created either from an imported posting (pass `posting`, company and
         *     title are snapshotted from it) or as free text (pass `company` and
         *     `title` directly). */
        JobApplication: {
            readonly id: number;
            posting?: number | null;
            company?: string;
            title?: string;
            location?: string;
            /** Format: uri */
            ad_url?: string;
            status?: components["schemas"]["StatusEnum"];
            readonly status_label: string;
            /** Format: date */
            applied_at?: string | null;
            /** Format: date */
            deadline?: string | null;
            contact_name?: string;
            contact_info?: string;
            notes?: string;
            /** Format: date */
            next_action_at?: string | null;
            readonly events: components["schemas"]["ApplicationEvent"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Lean row for list responses — no timeline.
         *
         *     The board renders hundreds of rows; shipping every row's full event
         *     history made the list payload grow with total activity. The detail
         *     endpoint still includes ``events``. */
        JobApplicationList: {
            readonly id: number;
            readonly posting: number | null;
            readonly company: string;
            readonly title: string;
            readonly location: string;
            /** Format: uri */
            readonly ad_url: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_label: string;
            /** Format: date */
            readonly applied_at: string | null;
            /** Format: date */
            readonly deadline: string | null;
            readonly contact_name: string;
            readonly contact_info: string;
            readonly notes: string;
            /** Format: date */
            readonly next_action_at: string | null;
            readonly match: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        Login: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        Logout: {
            refresh: string;
        };
        PaginatedJobApplicationListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["JobApplicationList"][];
        };
        /** @description One tracker row.
         *
         *     Created either from an imported posting (pass `posting`, company and
         *     title are snapshotted from it) or as free text (pass `company` and
         *     `title` directly). */
        PatchedJobApplication: {
            readonly id?: number;
            posting?: number | null;
            company?: string;
            title?: string;
            location?: string;
            /** Format: uri */
            ad_url?: string;
            status?: components["schemas"]["StatusEnum"];
            readonly status_label?: string;
            /** Format: date */
            applied_at?: string | null;
            /** Format: date */
            deadline?: string | null;
            contact_name?: string;
            contact_info?: string;
            notes?: string;
            /** Format: date */
            next_action_at?: string | null;
            readonly events?: components["schemas"]["ApplicationEvent"][];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description The authenticated user's own profile. */
        PatchedProfile: {
            readonly id?: number;
            /**
             * Användarnamn
             * @description Obligatoriskt. 150 tecken eller färre. Endast bokstäver, siffror och @/./+/-/_.
             */
            readonly username?: string;
            /**
             * E-postadress
             * Format: email
             */
            email?: string;
            /** Förnamn */
            first_name?: string;
            /** Efternamn */
            last_name?: string;
            readonly operator_id?: string;
        };
        PatchedResume: {
            headline?: string;
            summary?: string;
            readonly skills?: string[];
            skill_groups?: unknown;
            job_profiles?: unknown;
            readonly active_profile_id?: string;
            experience?: unknown;
            education?: unknown;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedSavedJobSearch: {
            readonly id?: number;
            label?: string;
            q?: string;
            regions?: unknown;
            municipalities?: unknown;
            fields?: string[];
            groups?: string[];
            remote?: boolean;
            match_cv?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        /** @description User model w/o password */
        PatchedUserDetails: {
            /** ID */
            readonly pk?: number;
            /**
             * Användarnamn
             * @description Obligatoriskt. 150 tecken eller färre. Endast bokstäver, siffror och @/./+/-/_.
             */
            username?: string;
            /**
             * E-postadress
             * Format: email
             */
            readonly email?: string;
            /** Förnamn */
            first_name?: string;
            /** Efternamn */
            last_name?: string;
        };
        /** @description The authenticated user's own profile. */
        Profile: {
            readonly id: number;
            /**
             * Användarnamn
             * @description Obligatoriskt. 150 tecken eller färre. Endast bokstäver, siffror och @/./+/-/_.
             */
            readonly username: string;
            /**
             * E-postadress
             * Format: email
             */
            email?: string;
            /** Förnamn */
            first_name?: string;
            /** Efternamn */
            last_name?: string;
            readonly operator_id: string;
        };
        ResendEmailVerification: {
            /** Format: email */
            email: string;
        };
        RestAuthDetail: {
            readonly detail: string;
        };
        Resume: {
            headline?: string;
            summary?: string;
            readonly skills: string[];
            skill_groups?: unknown;
            job_profiles?: unknown;
            readonly active_profile_id: string;
            experience?: unknown;
            education?: unknown;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ResumeUpload: {
            /** Format: uri */
            file: string;
        };
        /** @description Password change also signs out every other device. */
        RevokingPasswordChange: {
            new_password1: string;
            new_password2: string;
        };
        /** @description Password reset also signs out every other device. */
        RevokingPasswordResetConfirm: {
            new_password1: string;
            new_password2: string;
            uid: string;
            token: string;
        };
        SavedJobSearch: {
            readonly id: number;
            label?: string;
            q?: string;
            regions?: unknown;
            municipalities?: unknown;
            fields?: string[];
            groups?: string[];
            remote?: boolean;
            match_cv?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        SocialLogin: {
            access_token?: string;
            code?: string;
            id_token?: string;
        };
        /**
         * @description * `wishlist` - Sparad
         *     * `applied` - Ansökt
         *     * `screening` - Telefonintervju
         *     * `interview` - Intervju
         *     * `forwarded` - Skickad vidare
         *     * `offer` - Erbjudande
         *     * `accepted` - Accepterat
         *     * `rejected` - Avslag
         *     * `no_response` - Inget svar
         *     * `withdrawn` - Återkallad
         * @enum {string}
         */
        StatusEnum: "wishlist" | "applied" | "screening" | "interview" | "forwarded" | "offer" | "accepted" | "rejected" | "no_response" | "withdrawn";
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        /** @description User model w/o password */
        UserDetails: {
            /** ID */
            readonly pk: number;
            /**
             * Användarnamn
             * @description Obligatoriskt. 150 tecken eller färre. Endast bokstäver, siffror och @/./+/-/_.
             */
            username: string;
            /**
             * E-postadress
             * Format: email
             */
            readonly email: string;
            /** Förnamn */
            first_name?: string;
            /** Efternamn */
            last_name?: string;
        };
        VerifyEmail: {
            key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_applications_list: {
        parameters: {
            query?: {
                /** @description Earliest applied_at date. */
                from?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Free text over company, title and notes. */
                search?: string;
                /** @description Filter by status. */
                status?: string;
                /** @description Latest applied_at date. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobApplicationListList"];
                };
            };
        };
    };
    api_v1_applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobApplication"];
                "application/x-www-form-urlencoded": components["schemas"]["JobApplication"];
                "multipart/form-data": components["schemas"]["JobApplication"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"];
                };
            };
        };
    };
    api_v1_applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"];
                };
            };
        };
    };
    api_v1_applications_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobApplication"];
                "application/x-www-form-urlencoded": components["schemas"]["JobApplication"];
                "multipart/form-data": components["schemas"]["JobApplication"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"];
                };
            };
        };
    };
    api_v1_applications_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJobApplication"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJobApplication"];
                "multipart/form-data": components["schemas"]["PatchedJobApplication"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"];
                };
            };
        };
    };
    api_v1_applications_events_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this job application. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationEvent"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationEvent"];
                "multipart/form-data": components["schemas"]["ApplicationEvent"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationEvent"];
                };
            };
        };
    };
    api_v1_applications_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    api_v1_applications_tracked_urls_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_jobs_retrieve: {
        parameters: {
            query?: {
                /** @description Occupation-field concept id (repeatable). */
                field?: string;
                /** @description Occupation-group concept id (repeatable). */
                group?: string;
                limit?: number;
                /** @description Only jobs that match the user's CV (≥40%). */
                match_cv?: boolean;
                /** @description Municipality concept id (repeatable). */
                municipality?: string;
                offset?: number;
                /** @description Free text query. */
                q?: string;
                /** @description Region concept id (repeatable). */
                region?: string;
                /** @description Remote only. */
                remote?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_jobs_filters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_jobs_groups_retrieve: {
        parameters: {
            query?: {
                /** @description Occupation-field concept id. */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_jobs_municipalities_retrieve: {
        parameters: {
            query?: {
                /** @description Region concept id. */
                region?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_v1_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Profile"];
                "application/x-www-form-urlencoded": components["schemas"]["Profile"];
                "multipart/form-data": components["schemas"]["Profile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_v1_me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfile"];
                "multipart/form-data": components["schemas"]["PatchedProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    api_v1_me_resume_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    api_v1_me_resume_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Resume"];
                "application/x-www-form-urlencoded": components["schemas"]["Resume"];
                "multipart/form-data": components["schemas"]["Resume"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    api_v1_me_resume_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_me_resume_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedResume"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedResume"];
                "multipart/form-data": components["schemas"]["PatchedResume"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
        };
    };
    api_v1_me_resume_parse_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ResumeUpload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_me_resume_suggest_evidence_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_me_resume_suggest_skills_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_v1_me_saved_searches_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSearch"][];
                };
            };
        };
    };
    api_v1_me_saved_searches_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SavedJobSearch"];
                "application/x-www-form-urlencoded": components["schemas"]["SavedJobSearch"];
                "multipart/form-data": components["schemas"]["SavedJobSearch"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSearch"];
                };
            };
        };
    };
    api_v1_me_saved_searches_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSearch"];
                };
            };
        };
    };
    api_v1_me_saved_searches_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_me_saved_searches_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSavedJobSearch"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSavedJobSearch"];
                "multipart/form-data": components["schemas"]["PatchedSavedJobSearch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobSearch"];
                };
            };
        };
    };
    dj_rest_auth_google_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SocialLogin"];
                "application/x-www-form-urlencoded": components["schemas"]["SocialLogin"];
                "multipart/form-data": components["schemas"]["SocialLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialLogin"];
                };
            };
        };
    };
    dj_rest_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWT"];
                };
            };
        };
    };
    dj_rest_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokingPasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["RevokingPasswordChange"];
                "multipart/form-data": components["schemas"]["RevokingPasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontendPasswordReset"];
                "application/x-www-form-urlencoded": components["schemas"]["FrontendPasswordReset"];
                "multipart/form-data": components["schemas"]["FrontendPasswordReset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokingPasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["RevokingPasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["RevokingPasswordResetConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    dj_rest_auth_registration_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRegister"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailRegister"];
                "multipart/form-data": components["schemas"]["EmailRegister"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailRegister"];
                };
            };
        };
    };
    dj_rest_auth_registration_account_confirm_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmail"];
                };
            };
        };
    };
    dj_rest_auth_registration_resend_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendEmailVerification"];
                "application/x-www-form-urlencoded": components["schemas"]["ResendEmailVerification"];
                "multipart/form-data": components["schemas"]["ResendEmailVerification"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendEmailVerification"];
                };
            };
        };
    };
    dj_rest_auth_registration_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmail"];
                };
            };
        };
    };
    dj_rest_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    dj_rest_auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    dj_rest_auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    dj_rest_auth_user_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["UserDetails"];
                "multipart/form-data": components["schemas"]["UserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    dj_rest_auth_user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserDetails"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserDetails"];
                "multipart/form-data": components["schemas"]["PatchedUserDetails"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetails"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
}
