# Generated by Django 5.2.10 on 2026-06-12 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("ad_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wishlist", "Sparad"),
                            ("applied", "Ansökt"),
                            ("screening", "Telefonintervju"),
                            ("interview", "Intervju"),
                            ("forwarded", "Skickad vidare"),
                            ("offer", "Erbjudande"),
                            ("accepted", "Accepterat"),
                            ("rejected", "Avslag"),
                            ("no_response", "Inget svar"),
                            ("withdrawn", "Återkallad"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
                ("applied_at", models.DateField(blank=True, null=True)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_info", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("next_action_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateField()),
                ("note", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wishlist", "Sparad"),
                            ("applied", "Ansökt"),
                            ("screening", "Telefonintervju"),
                            ("interview", "Intervju"),
                            ("forwarded", "Skickad vidare"),
                            ("offer", "Erbjudande"),
                            ("accepted", "Accepterat"),
                            ("rejected", "Avslag"),
                            ("no_response", "Inget svar"),
                            ("withdrawn", "Återkallad"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=50)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("webpage_url", models.URLField(blank=True, max_length=500)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="uniq_jobposting_source_external_id",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="core.jobposting",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="core.jobposting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("posting__isnull", False)),
                fields=("owner", "posting"),
                name="uniq_jobapplication_owner_posting",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "posting"), name="uniq_favorite_user_posting"
            ),
        ),
    ]
