# Generated by Django 5.2.10 on 2026-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
