# Generated by Django 5.2.10 on 2026-01-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization_employerprofile_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="core.jobposting",
            ),
        ),
    ]
