# Generated by Django 5.2.10 on 2026-06-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobapplication_deadline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
