# Generated by Django 5.2.10 on 2026-01-13 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobapplication_job_posting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="company",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="job_posting",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="role",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="posting",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.jobposting",
            ),
            preserve_default=False,
        ),
    ]
