# Generated by Django 5.2.10 on 2026-01-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_jobapplication_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="cover_letter",
        ),
    ]
