# Generated by Django 5.2.10 on 2026-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_update_site_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorprofile",
            name="deletion_warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
