# Generated by Django 5.2.10 on 2026-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_operatorprofile_deletion_warned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorprofile",
            name="weekly_summary_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedjobsearch",
            name="digest_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
