# Generated by Django 5.2.10 on 2026-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_jobapplication_uniq_jobapplication_owner_posting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("application.created", "Application created"),
                    ("application.deleted", "Application deleted"),
                    ("applications.disclosed", "Applications disclosed"),
                    (
                        "applications.disclosed_partner",
                        "Applications disclosed to partner",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
