# Generated by Django 5.2.10 on 2026-06-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_partnerclient_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("application.created", "Application created"),
                    ("application.deleted", "Application deleted"),
                    ("applications.disclosed", "Applications disclosed"),
                    (
                        "applications.disclosed_partner",
                        "Applications disclosed to partner",
                    ),
                    ("identity.verified", "Identity verified"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_number_hash", models.CharField(max_length=64, unique=True)),
                ("method", models.CharField(default="bankid-mock", max_length=32)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
