# Generated by Django 5.2.10 on 2026-06-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_auditlog_action_applicantprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="webpage_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
