# Generated by Django 5.2.10 on 2026-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jobposting_description_jobposting_webpage_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("application.created", "Application created"),
                    ("application.deleted", "Application deleted"),
                    ("applications.disclosed", "Applications disclosed"),
                    (
                        "applications.disclosed_partner",
                        "Applications disclosed to partner",
                    ),
                    ("identity.verified", "Identity verified"),
                    ("account.deleted", "Account deleted"),
                ],
                max_length=64,
            ),
        ),
    ]
