# Generated by Django 5.2

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_apply_by(apps, schema_editor):
    JobApplication = apps.get_model("core", "JobApplication")
    for app in JobApplication.objects.filter(status="wishlist").iterator():
        if app.deadline:
            app.apply_by = app.deadline
            app.apply_by_is_auto = False
        else:
            if app.created_at:
                base = timezone.localtime(app.created_at).date()
            else:
                base = timezone.localdate()
            app.apply_by = base + timedelta(days=14)
            app.apply_by_is_auto = True
        app.save(update_fields=["apply_by", "apply_by_is_auto"])


def clear_apply_by(apps, schema_editor):
    JobApplication = apps.get_model("core", "JobApplication")
    JobApplication.objects.all().update(apply_by=None, apply_by_is_auto=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_site_jobbdjungeln"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="apply_by",
            field=models.DateField(
                blank=True,
                help_text="Sök senast — auto from deadline or created_at+14, editable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="apply_by_is_auto",
            field=models.BooleanField(
                default=True,
                help_text="False when the user set apply_by themselves.",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="intent",
            field=models.CharField(
                choices=[("active", "Ska söka"), ("paused", "Lagd på is")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_apply_by, clear_apply_by),
    ]
