# Generated by Django 5.2

from django.db import migrations, models
from django.utils import timezone


def backfill_match_snapshots(apps, schema_editor):
    """Score rows that have ad text or a linked posting."""
    JobApplication = apps.get_model("core", "JobApplication")
    Resume = apps.get_model("core", "Resume")
    # Historical models lack Python helpers — skip live scoring in migration
    # and leave scores null until the next save/apply. Keeps migration fast
    # and reversible without importing current matching code against old
    # model state.
    JobApplication.objects.filter(match_version=2).update(match_version=2)


def clear_match_snapshots(apps, schema_editor):
    JobApplication = apps.get_model("core", "JobApplication")
    JobApplication.objects.all().update(
        match_score=None,
        match_snapshot={},
        match_scored_at=None,
        match_profile_id="",
        match_version=2,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_jobapplication_apply_by_intent_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="match_profile_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="match_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="match_scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="match_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="match_version",
            field=models.IntegerField(default=2),
        ),
        migrations.RunPython(backfill_match_snapshots, clear_match_snapshots),
    ]
