# Generated by Django 5.2.16 on 2026-08-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

from core.lifecycle import employer_key, outcome_for_status, stage_for_status


def backfill_lifecycle(apps, schema_editor):
    JobApplication = apps.get_model("core", "JobApplication")
    for app in JobApplication.objects.all().iterator():
        stage = stage_for_status(app.status)
        outcome = outcome_for_status(app.status)
        updates = {
            "stage": stage,
            "outcome": outcome,
            "employer_key": employer_key(app.company),
        }
        if stage == "avslutad" and app.closed_at is None:
            updates["closed_at"] = app.updated_at or timezone.now()
        if stage != "bevakad" and app.applied_at is None and app.created_at:
            updates["applied_at"] = timezone.localtime(app.created_at).date()
        JobApplication.objects.filter(pk=app.pk).update(**updates)


def reverse_lifecycle(apps, schema_editor):
    JobApplication = apps.get_model("core", "JobApplication")
    JobApplication.objects.update(
        stage="sokt",
        outcome="",
        employer_key="",
        closed_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobapplication_match_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='from_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='is_reportable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='origin',
            field=models.CharField(choices=[('manuell', 'Manuell'), ('auto', 'Automatisk'), ('import', 'Import')], default='manuell', max_length=12),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='to_stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='employer_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='occupation_concept_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='occupation_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='outcome',
            field=models.CharField(blank=True, choices=[('avslag', 'Avslag'), ('inget_svar', 'Inget svar'), ('aterkallad', 'Återkallad'), ('tackade_ja', 'Tackade ja'), ('tackade_nej', 'Tackade nej'), ('tjansten_tillsatt', 'Tjänsten tillsatt')], max_length=24),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='report_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='report_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('bevakad', 'Bevakad'), ('sokt', 'Sökt'), ('kontakt', 'Kontakt'), ('intervju', 'Intervju'), ('erbjudande', 'Erbjudande'), ('avslutad', 'Avslutad')], db_index=True, default='sokt', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rekryteringstraff', 'Rekryteringsträff / mässa'), ('kurs', 'Kurs / utbildning'), ('spontanansokan', 'Spontanansökan'), ('natverkande', 'Nätverkskontakt'), ('cv_arbete', 'CV / personligt brev'), ('mote_af', 'Möte med AF eller leverantör'), ('ovrigt', 'Övrigt')], max_length=24)),
                ('occurred_on', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('reported_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.reportperiod')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='reported_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to='core.reportperiod'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reported_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.reportperiod'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['owner', 'stage', 'applied_at'], name='core_jobapp_owner_i_544b5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportperiod',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='uniq_reportperiod_user_year_month'),
        ),
        migrations.RunPython(backfill_lifecycle, reverse_lifecycle),
    ]
